# Generated by Django 5.2.8 on 2025-11-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('repo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port', models.PositiveIntegerField()),
                ('running', models.BooleanField(default=False)),
            ],
        ),
    ]
