# Generated by Django 5.2.4 on 2025-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deployedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedproject',
            name='pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployedproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deployedproject',
            name='port',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
