# Generated by Django 5.2.4 on 2025-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_deployedproject_pid_alter_deployedproject_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployedproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='deployedproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='deployedproject',
            index=models.Index(fields=['port'], name='app_deploye_port_f9a607_idx'),
        ),
        migrations.AddIndex(
            model_name='deployedproject',
            index=models.Index(fields=['pid'], name='app_deploye_pid_101c6a_idx'),
        ),
    ]
