# Generated by Django 5.2.4 on 2025-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_deployedproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedproject',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='deployedproject',
            index=models.Index(fields=['name'], name='app_deploye_name_2c83ec_idx'),
        ),
    ]
